---
title: 'BIOSTAT 203B: Homework 4'
author: "Chad Pickering"
date: "3/16/2018"
output: html_document
---

#### The following code connects to spark, the data, etc.

```{r, warning=FALSE, message=FALSE}
library(sparklyr)
library(dplyr)
library(ggplot2)
Sys.setenv(SPARK_HOME="/usr/lib/spark")
config <- spark_config()
sc <- spark_connect(master = "yarn-client", config = config)
flights_tbl <- tbl(sc, 'flights')
airports_tbl <- tbl(sc, 'airports')
flights_tbl %>% print(width = Inf) %>% head(3) ## head of the data - delete later
```

## 1. Map the top 10 busiest airports (in 1995). Size of dots should reflect the number of flights through that destination.

#### "Busiest" is defined as the sum of flights arriving and departing a particular airport per unit time.

```{r}
origin_tbl <- flights_tbl %>%
  filter(year == 1995) %>%
  group_by(origin) %>%
  count() %>%
  arrange(desc(n)) %>%
  collect()

dest_tbl <- flights_tbl %>%
  filter(year == 1995) %>%
  group_by(dest) %>%
  count() %>% 
  arrange(desc(n)) %>%
  collect()

top_10_busy <- merge(origin_tbl, dest_tbl, by.x="origin", by.y="dest") %>%
  mutate(total = n.x + n.y) %>%
  arrange(desc(total)) %>%
  rename(airport = origin) %>%
  select(airport, total) %>%
  collect() %>%
  head(10)

top_10_airports <- airports_tbl %>% 
  filter(faa %in% top_10_busy$airport) %>%
  select(faa, lon, lat)

top_10_final_tbl <- merge(top_10_busy, 
                          top_10_airports, by.x="airport", by.y="faa")
top_10_final_tbl$lon <- as.numeric(as.character(top_10_final_tbl$lon))
top_10_final_tbl$lat <- as.numeric(as.character(top_10_final_tbl$lat))

usa <- map_data("usa")
ggplot() + 
  geom_polygon(data = usa, aes(x=long, y = lat, group = group), fill = "aliceblue", color = "grey70") + 
  coord_fixed(1.3) +
  geom_point(data = top_10_final_tbl, 
             mapping = aes(x = lon, y = lat, color = airport, size = total)) +
  labs(title = "Top 10 Busiest U.S. Airports in 1995",
       subtitle = "Sum of Arrival and Departure Counts per Airport",
       x = "Longitude",
       y = "Latitude")
```



