---
title: 'Biostat M280 Homework #1'
author: "Chad Pickering"
date: "1/26/2018"
output: html_document
---

## Q1. Git/GitHub

**1. Apply for the Student Developer Pack at GitHub using your UCLA email.**    

Done on January 21. My GitHub handle is @cepickering .  

**2. Create a private repository `biostat-m280-2018-winter`; add `Hua-Zhou` and `juhkim111` as your collaborators with write permission.**

Done on January 21. If write permission was somehow not granted, please contact me as soon as possible.  

**3. Top directories of the repository should be `hw1`, `hw2`, ... Maintain two branches `master` and `develop`.**  

Done on January 21. One subdirectory, `hw1` has been made, and the subsequent subdirectories will be created and used as the homeworks are assigned.  

**4. After each homework due date, teaching assistant and instructor will check out your master branch for grading. Tag each of your homework submissions with tag names `hw1`, `hw2`, ... Tagging time will be used as your submission time.**  

Understood.  

## Q2. Linux Shell Commands  

#### Question 1.  

**How many persons are in the data set (statisticians call this `n`)?**  

```{bash}
awk '{print $2}' /home/m280-data/hw1/merge-geno.fam | sort | uniq | wc -l
```

**How many SNPs are in the data set (statisticians call this `p`)?**  

```{bash}
awk '{print $2}' /home/m280-data/hw1/merge-geno.bim | sort | uniq | wc -l
```

#### Question 2.  

**Which chromosomes does this data set contain?**  

```{bash}
awk '{print $1}' /home/m280-data/hw1/merge-geno.bim | uniq
```

**How many SNPs are in each chromosome?** 

```{bash}
awk '{print $1}' /home/m280-data/hw1/merge-geno.bim | sort -n | uniq -c
```

#### Question 3.  

**MAP4 (microtubule-associated protein 4) is a gene on chromosome 3 spanning positions 47,892,180 bp -- 48,130,769 bp. How many SNPs are located within MAP4 gene?**  

```{bash}
awk '{if($1 == 3 && $4 >= 47892180 && $4 <= 48130769) {print $2}}' /home/m280-data/hw1/merge-geno.bim | uniq | wc -l
```

#### Question 4.

**Statistical geneticists often have to reformat a data set to feed into various analysis programs. For example, to use the Mendel software we have to reformat the data set to be read by Mendel. Mendel's SNP definition file is similar to the plink `bim` file but has format `SNP ID`, `Chromosome`, `Base Pair Position` with each field separated by a comma. Write a Linux shell command to convert `merge-geno.bim` to Mendel SNP definition file.**   
      
```{bash}
awk '{print $2","$1","$4}' /home/m280-data/hw1/merge-geno.bim > hw1_def_file.txt | sed -i '1 i\2.40=FILE FORMAT VERSION NUMBER.\n8348674=NUMBER OF SNPS LISTED HERE.' hw1_def_file.txt ; head -20 hw1_def_file.txt
```
    
**Mendel's pedigree file is similar to the plink `fam` file but has format `Family ID`, `Person ID`, `Father ID`, `Mother ID`, `Sex` coded as M or F, `Twin Status` with each field separated by a comma. Write a Linux shell command to convert `merge-geno.fam` to Mendel pedigree file. Since twin status is not available in plink format, we put nothing for that field. Also Mendel limits Person ID to have length less than or equal to 8 characters, so we have to strip the string `T2DG` from the IDs.**  

```{bash}
sed 's/ /,/g' /home/m280-data/hw1/merge-geno.fam | sed 's/T2DG//g' | sed 's/\0\b//g' | awk '{if($5==1) $5="M"; else $5="F"}{print}' FS=, OFS=, > hw1_ped_file.txt ; head -20 hw1_ped_file.txt
```








